In [4]:
import http.client
import json
import pandas as pd
import datetime
import numpy as np

## Récupération des données de matchs

In [5]:
connection = http.client.HTTPConnection('api.football-data.org')
headers = { 'X-Auth-Token': '52209beef1bc4a4e8b08fbf89163915f' }

connection.request('GET', 'https://api.football-data.org/v2/competitions/FL1/matches', None, headers )
matchs_fr = json.loads(connection.getresponse().read().decode())
connection.request('GET', 'https://api.football-data.org/v2/competitions/CL/matches', None, headers )
matchs_cl = json.loads(connection.getresponse().read().decode())
connection.request('GET', 'https://api.football-data.org/v2/competitions/PL/matches', None, headers )
matchs_eng = json.loads(connection.getresponse().read().decode())
connection.request('GET', 'https://api.football-data.org/v2/competitions/PD/matches', None, headers )
matchs_esp = json.loads(connection.getresponse().read().decode())
connection.request('GET', 'https://api.football-data.org/v2/competitions/SA/matches', None, headers )
matchs_ita = json.loads(connection.getresponse().read().decode())
connection.request('GET', 'https://api.football-data.org/v2/competitions/PPL/matches', None, headers )
matchs_pt = json.loads(connection.getresponse().read().decode())

In [6]:
df_fr=pd.DataFrame(matchs_fr['matches'])
df_cl=pd.DataFrame(matchs_cl['matches'])
df_eng=pd.DataFrame(matchs_eng['matches'])
df_esp=pd.DataFrame(matchs_esp['matches'])
df_ita=pd.DataFrame(matchs_ita['matches'])
df_pt=pd.DataFrame(matchs_pt['matches'])


columns=['id','utcDate','status','score','homeTeam','awayTeam']

fr_names=df_fr[columns]
cl_names=df_cl[columns]
eng_names=df_eng[columns]
esp_names=df_esp[columns]
ita_names=df_ita[columns]
pt_names=df_pt[columns]


df_matchs=pd.DataFrame(columns=['id','utcDate','status','score','homeTeam','awayTeam'])
df_matchs=df_matchs.append(fr_names,ignore_index=True)
df_matchs=df_matchs.append(eng_names,ignore_index=True)
df_matchs=df_matchs.append(esp_names,ignore_index=True)
df_matchs=df_matchs.append(ita_names,ignore_index=True)
df_matchs=df_matchs.append(cl_names,ignore_index=True)
df_matchs=df_matchs.append(pt_names,ignore_index=True)

#df_matchs=df_matchs.drop_duplicates()
df_matchs

,id,utcDate,status,score,homeTeam,awayTeam
0,267926,2019-08-09T18:45:00Z,FINISHED,"{'winner': 'AWAY_TEAM', 'duration': 'REGULAR',...","{'id': 548, 'name': 'AS Monaco FC'}","{'id': 523, 'name': 'Olympique Lyonnais'}"
1,267922,2019-08-10T15:30:00Z,FINISHED,"{'winner': 'AWAY_TEAM', 'duration': 'REGULAR',...","{'id': 516, 'name': 'Olympique de Marseille'}","{'id': 547, 'name': 'Stade de Reims'}"
2,267919,2019-08-10T18:00:00Z,FINISHED,"{'winner': 'AWAY_TEAM', 'duration': 'REGULAR',...","{'id': 518, 'name': 'Montpellier HSC'}","{'id': 529, 'name': 'Stade Rennais FC 1901'}"
3,267923,2019-08-10T18:00:00Z,FINISHED,"{'winner': 'HOME_TEAM', 'duration': 'REGULAR',...","{'id': 522, 'name': 'OGC Nice'}","{'id': 530, 'name': 'Amiens SC'}"
4,267924,2019-08-10T18:00:00Z,FINISHED,"{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...","{'id': 512, 'name': 'Stade Brestois 29'}","{'id': 511, 'name': 'Toulouse FC'}"
...,...,...,...,...,...,...
2024,274477,2020-07-26T00:00:00Z,SCHEDULED,"{'winner': None, 'duration': 'REGULAR', 'fullT...","{'id': 1903, 'name': 'Sport Lisboa e Benfica'}","{'id': 498, 'name': 'Sporting Clube de Portugal'}"
2025,274478,2020-07-26T00:00:00Z,SCHEDULED,"{'winner': None, 'duration': 'REGULAR', 'fullT...","{'id': 5620, 'name': 'Vitória FC'}","{'id': 5568, 'name': 'Os Belenenses Futebol'}"
2026,274479,2020-07-26T00:00:00Z,SCHEDULED,"{'winner': None, 'duration': 'REGULAR', 'fullT...","{'id': 5530, 'name': 'CD Santa Clara'}","{'id': 5543, 'name': 'Vitória SC'}"
2027,274480,2020-07-26T00:00:00Z,SCHEDULED,"{'winner': None, 'duration': 'REGULAR', 'fullT...","{'id': 5601, 'name': 'Portimonense SC'}","{'id': 5544, 'name': 'CD Aves'}"
2028,274481,2020-07-26T00:00:00Z,SCHEDULED,"{'winner': None, 'duration': 'REGULAR', 'fullT...","{'id': 810, 'name': 'Boavista FC'}","{'id': 496, 'name': 'Rio Ave FC'}"

## On garde les matchs terminés pour l'apprentissage

In [7]:
df_finished=df_matchs.loc[df_matchs["status"]=="FINISHED"]
df_finished[1140:1150]

,id,utcDate,status,score,homeTeam,awayTeam
1383,279468,2020-02-22T19:45:00Z,FINISHED,"{'winner': 'DRAW', 'duration': 'REGULAR', 'ful...","{'id': 99, 'name': 'ACF Fiorentina'}","{'id': 98, 'name': 'AC Milan'}"
1384,279473,2020-02-23T11:30:00Z,FINISHED,"{'winner': 'AWAY_TEAM', 'duration': 'REGULAR',...","{'id': 107, 'name': 'Genoa CFC'}","{'id': 110, 'name': 'SS Lazio'}"
1385,279469,2020-02-23T17:00:00Z,FINISHED,"{'winner': 'HOME_TEAM', 'duration': 'REGULAR',...","{'id': 100, 'name': 'AS Roma'}","{'id': 5890, 'name': 'US Lecce'}"
1386,279479,2020-02-29T14:00:00Z,FINISHED,"{'winner': 'HOME_TEAM', 'duration': 'REGULAR',...","{'id': 110, 'name': 'SS Lazio'}","{'id': 103, 'name': 'Bologna FC 1909'}"
1387,279478,2020-02-29T19:45:00Z,FINISHED,"{'winner': 'HOME_TEAM', 'duration': 'REGULAR',...","{'id': 113, 'name': 'SSC Napoli'}","{'id': 586, 'name': 'Torino FC'}"
1388,279486,2020-03-01T14:00:00Z,FINISHED,"{'winner': 'AWAY_TEAM', 'duration': 'REGULAR',...","{'id': 5890, 'name': 'US Lecce'}","{'id': 102, 'name': 'Atalanta BC'}"
1389,279484,2020-03-01T17:00:00Z,FINISHED,"{'winner': 'AWAY_TEAM', 'duration': 'REGULAR',...","{'id': 104, 'name': 'Cagliari Calcio'}","{'id': 100, 'name': 'AS Roma'}"
1390,279481,2020-03-08T12:30:00Z,FINISHED,"{'winner': 'AWAY_TEAM', 'duration': 'REGULAR',...","{'id': 112, 'name': 'Parma Calcio 1913'}","{'id': 1107, 'name': 'SPAL 2013'}"
1391,279480,2020-03-08T14:00:00Z,FINISHED,"{'winner': 'AWAY_TEAM', 'duration': 'REGULAR',...","{'id': 98, 'name': 'AC Milan'}","{'id': 107, 'name': 'Genoa CFC'}"
1392,279483,2020-03-08T14:00:00Z,FINISHED,"{'winner': 'HOME_TEAM', 'duration': 'REGULAR',...","{'id': 584, 'name': 'UC Sampdoria'}","{'id': 450, 'name': 'Hellas Verona FC'}"

### On numérise les données afin de pouvoir les analyser

### Victoires / Défaites consecutives

In [8]:
def recupDate(x):
    annee=x[0:4]
    mois=x[5:7]
    jour=x[8:10]
    date=datetime.datetime(int(annee),int(mois),int(jour))
    return date

### Récupération du nom de chaque équipe

In [9]:
def recupTeam(x):
    string=str(x)
    chaine=("'name': ")
    long=len(chaine)
    result=string.find(chaine)
    if result>-1:
        debut=result+long
        i=0
        name=""
        while i==0:
            if string[debut]=='}':
                i=1
                break
            name=name+string[debut]
            debut+=1
    name=name.replace("'","") 
    return name

### Récupération de l'id de chaque équipe

In [10]:
def recupId(x):
    string=str(x)
    chaine=("'id': ")
    long=len(chaine)
    result=string.find(chaine)
    if result>-1:
        debut=result+long
        i=0
        ident=""
        while i==0:
            if string[debut]==',':
                i=1
                break
            ident=ident+string[debut]
            debut+=1
    ident=ident.replace(" ","") 
    return ident

### Récupération du résultat du match

In [11]:
def winner(score):
    string=str(score)
    chaine=("'winner':")
    long=len(chaine)
    result=string.find(chaine)
    if result>-1:
        debut=result+long
        i=0
        winner=""
        while i==0:
            if string[debut]==',':
                i=1
                break
            winner=winner+string[debut]
            debut+=1
    if (winner==" 'DRAW'"):
        winner=0            
    if (winner==" 'HOME_TEAM'"):
        winner=1
    if (winner==" 'AWAY_TEAM'"):
        winner=2
    if (winner==" None"):
        winner=None
    
    return winner

### Récupération du nombre de buts à la mi-temps et à la fin du match

In [12]:
def goal_time(score,nb):
    string=str(score)
    if nb==1:
        chaine=("'halfTime': {")
    if nb==2:
        chaine=("'fullTime': {")
    long=len(chaine)
    half=string.find(chaine)
    if half>-1:
        debut=half+long
        i=0
        goalHomeTeam=""
        while i==0:
            if string[debut]=='}':
                i=1
                break
            goalHomeTeam=goalHomeTeam+string[debut]
            debut+=1
    test=goalHomeTeam.split(",")
    goalHomeTeam=test[0].replace("'homeTeam': ","") 
    goalAwayTeam=test[1].replace(" 'awayTeam': ","")
    return goalHomeTeam, goalAwayTeam

### Comptage des victoires et défaites consécutives

In [13]:
def compte_win(df_verif,name):
    win_cons=0
    for index, row in df_verif.iterrows():
        home=row["homeTeam"]
        away=row["awayTeam"]
        score=row["score"]
        if ((home==name) and (score==1)):
            win_cons+=1
        if ((away==name) and (score==2)):
            win_cons+=1
        if ((home==name) and (score==2)):
            win_cons=0
        if (((away==name) and (score==1)) or (score==0)):
            win_cons=0
    return win_cons



def compte_lose(df_verif,name):
    lose_cons=0
    for index, row in df_verif.iterrows():
        home=row["homeTeam"]
        away=row["awayTeam"]
        score=row["score"]
        if ((home==name) and (score==2)):
            lose_cons+=1
        if ((away==name) and (score==1)):
            lose_cons+=1
        if ((home==name) and (score==1)):
            lose_cons=0
        if (((away==name) and (score==2)) or (score==0)):
            lose_cons=0
    return lose_cons

In [14]:
def victoire_consecutives(x,df):
    date=x['date']
    anterieur=df.loc[df['date']< date]    
    home=x["homeTeam"]
    away=x["awayTeam"]
    nb_home=0
    nb_away=0
    if(anterieur.empty): 
        return nb_home,nb_away 
    else:
        verifHome=anterieur.loc[anterieur['homeTeam']==home]
        verifHome2=anterieur.loc[anterieur['awayTeam']==home]
        
        verifAway=anterieur.loc[anterieur['homeTeam']==away]
        verifAway2=anterieur.loc[anterieur['awayTeam']==away]
        
        df_verif=pd.concat([verifHome,verifHome2])
        df_verif=df_verif.sort_values(by = 'date')
        
        df_verif2=pd.concat([verifAway,verifAway2])
        df_verif2=df_verif2.sort_values(by = 'date')
        
        if (df_verif.empty):
                nb_home=-1
        else:
            nb_home=compte_win(df_verif,home)
        
        if(df_verif2.empty):
            nb_away=-1
        
        else:
            nb_away=compte_win(df_verif2,away)
        
    return nb_home,nb_away

In [15]:
def defaites_consecutives(x,df):
    date=x['date']
    anterieur=df.loc[df['date']< date]    
    home=x["homeTeam"]
    away=x["awayTeam"]
    nb_home=0
    nb_away=0
    if(anterieur.empty): 
        return nb_home,nb_away 
    else:
        verifHome=anterieur.loc[anterieur['homeTeam']==home]
        verifHome2=anterieur.loc[anterieur['awayTeam']==home]
        
        verifAway=anterieur.loc[anterieur['homeTeam']==away]
        verifAway2=anterieur.loc[anterieur['awayTeam']==away]
        
        df_verif=pd.concat([verifHome,verifHome2])
        df_verif=df_verif.sort_values(by = 'date')
        
        df_verif2=pd.concat([verifAway,verifAway2])
        df_verif2=df_verif2.sort_values(by = 'date')
        
        if (df_verif.empty):
                nb_home=-1
        else:
            nb_home=compte_lose(df_verif,home)
        
        if(df_verif2.empty):
            nb_away=-1
        
        else:
            nb_away=compte_lose(df_verif2,away)
        
    return nb_home,nb_away

## Attribution des données au dataframe final

In [16]:
df_final=pd.DataFrame()
df_final['id_match']=df_finished['id']
df_final['date']=df_finished['utcDate'].apply(lambda x: recupDate(x))
df_final['idHomeTeam']=df_finished['homeTeam'].apply(lambda x: recupId(x))
df_final['idAwayTeam']=df_finished['awayTeam'].apply(lambda x: recupId(x))
df_final['homeTeam']=df_finished['homeTeam'].apply(lambda x: recupTeam(x))
df_final['awayTeam']=df_finished['awayTeam'].apply(lambda x: recupTeam(x))
df_final['score']=df_finished['score'].apply(lambda x: winner(x))
df_final['goalHomeTeam_HalfTime'], df_final['goalAwayTeam_HalfTime']=zip(*df_finished['score']
                                                                       .apply(lambda x: goal_time(x,1)))
df_final['goalHomeTeam_FullTime'], df_final['goalAwayTeam_FullTime']=zip(*df_finished['score']
                                                                       .apply(lambda x: goal_time(x,2)))
df_final['win_cons_home'], df_final['win_cons_away']=zip(*df_final.apply(lambda x: victoire_consecutives(x,df_final),axis=1))
df_final['lose_cons_home'], df_final['lose_cons_away']=zip(*df_final.apply(lambda x: defaites_consecutives(x,df_final),axis=1))
df_final.head()

,id_match,date,idHomeTeam,idAwayTeam,homeTeam,awayTeam,score,goalHomeTeam_HalfTime,goalAwayTeam_HalfTime,goalHomeTeam_FullTime,goalAwayTeam_FullTime,win_cons_home,win_cons_away,lose_cons_home,lose_cons_away
0,267926,2019-08-09,548,523,AS Monaco FC,Olympique Lyonnais,2.0,0,2,0,3,-1,-1,-1,-1
1,267922,2019-08-10,516,547,Olympique de Marseille,Stade de Reims,2.0,0,0,0,2,-1,-1,-1,-1
2,267919,2019-08-10,518,529,Montpellier HSC,Stade Rennais FC 1901,2.0,0,1,0,1,-1,-1,-1,-1
3,267923,2019-08-10,522,530,OGC Nice,Amiens SC,1.0,1,0,2,1,-1,-1,-1,-1
4,267924,2019-08-10,512,511,Stade Brestois 29,Toulouse FC,0.0,1,0,1,1,-1,-1,-1,-1

## Puissance-Teams

In [17]:
teams_puiss=pd.read_csv(r"Teams_puiss.csv",sep=";",index_col=0)
teams_puiss

        shortName                     name            name_web  puissance
0        Toulouse              Toulouse FC            Toulouse       1065
1           Brest        Stade Brestois 29               Brest       2156
2       Marseille   Olympique de Marseille  OlympiqueMarseille       4008
3     Montpellier          Montpellier HSC         Montpellier       3029
4           Lille                Lille OSC               Lille       4207
..            ...                      ...                 ...        ...
172    Belenenses    Os Belenenses Futebol          Belenenses       1589
173      Marítimo              CS Marítimo            Marítimo       1672
174  Portimonense          Portimonense SC        Portimonense       1067
175         Braga  Sporting Clube de Braga       SportingBraga       5314
176    Vitória FC               Vitória FC    VitóriaGuimarães       3593

[160 rows x 4 columns]

In [18]:
def puissance(name,df):
    puiss=df["puissance"].loc[df["name"]==name]
    puiss=puiss.values
    if(puiss):
        return int(puiss)
    else:
        return 100

In [19]:
df_final['puissance_homeTeam']=df_final['homeTeam'].apply(lambda x: puissance(x,teams_puiss))
df_final['puissance_awayTeam']=df_final['awayTeam'].apply(lambda x: puissance(x,teams_puiss))
df_final

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  after removing the cwd from sys.path.

,id_match,date,idHomeTeam,idAwayTeam,homeTeam,awayTeam,score,goalHomeTeam_HalfTime,goalAwayTeam_HalfTime,goalHomeTeam_FullTime,goalAwayTeam_FullTime,win_cons_home,win_cons_away,lose_cons_home,lose_cons_away,puissance_homeTeam,puissance_awayTeam
0,267926,2019-08-09,548,523,AS Monaco FC,Olympique Lyonnais,2.0,0,2,0,3,-1,-1,-1,-1,2409,6154
1,267922,2019-08-10,516,547,Olympique de Marseille,Stade de Reims,2.0,0,0,0,2,-1,-1,-1,-1,4008,3054
2,267919,2019-08-10,518,529,Montpellier HSC,Stade Rennais FC 1901,2.0,0,1,0,1,-1,-1,-1,-1,3029,4815
3,267923,2019-08-10,522,530,OGC Nice,Amiens SC,1.0,1,0,2,1,-1,-1,-1,-1,2803,2045
4,267924,2019-08-10,512,511,Stade Brestois 29,Toulouse FC,0.0,1,0,1,1,-1,-1,-1,-1,2156,1065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1968,274424,2020-06-23,5620,496,Vitória FC,Rio Ave FC,2.0,1,1,1,2,0,0,1,1,3593,100
1969,274423,2020-06-23,1903,5530,Sport Lisboa e Benfica,CD Santa Clara,2.0,0,1,3,4,1,0,0,0,6562,3175
1970,274419,2020-06-23,503,810,FC Porto,Boavista FC,1.0,0,0,4,0,0,2,0,0,6206,2325
1971,274427,2020-06-24,1049,507,CD Tondela,FC Paços de Ferreira,2.0,0,2,1,3,0,1,1,0,1729,1215
1972,274422,2020-06-24,583,5531,Moreirense FC,FC Famalicão,0.0,0,0,1,1,0,0,0,0,1842,2300

In [20]:
columns=["puissance_homeTeam","puissance_awayTeam",
         "win_cons_home","win_cons_away","lose_cons_home","lose_cons_away","score"]
df_final_data=df_final[columns]
df_final_data=df_final_data.dropna()
df_final_data

,puissance_homeTeam,puissance_awayTeam,win_cons_home,win_cons_away,lose_cons_home,lose_cons_away,score
0,2409,6154,-1,-1,-1,-1,2.0
1,4008,3054,-1,-1,-1,-1,2.0
2,3029,4815,-1,-1,-1,-1,2.0
3,2803,2045,-1,-1,-1,-1,1.0
4,2156,1065,-1,-1,-1,-1,0.0
...,...,...,...,...,...,...,...
1968,3593,100,0,0,1,1,2.0
1969,6562,3175,1,0,0,0,2.0
1970,6206,2325,0,2,0,0,1.0
1971,1729,1215,0,1,1,0,2.0
1972,1842,2300,0,0,0,0,0.0

In [21]:
df_final=df_final.dropna()

In [22]:
split=int(df_final.shape[0]/10)
df_test=df_final.tail(split)
df_test

,id_match,date,idHomeTeam,idAwayTeam,homeTeam,awayTeam,score,goalHomeTeam_HalfTime,goalAwayTeam_HalfTime,goalHomeTeam_FullTime,goalAwayTeam_FullTime,win_cons_home,win_cons_away,lose_cons_home,lose_cons_away,puissance_homeTeam,puissance_awayTeam
1812,274264,2019-11-04,5601,5530,Portimonense SC,CD Santa Clara,0.0,1,0,1,1,0,0,1,0,1067,3175
1813,274272,2019-11-08,5544,5533,CD Aves,Gil Vicente FC,2.0,1,2,1,2,0,1,8,0,1159,1346
1814,274268,2019-11-09,496,5620,Rio Ave FC,Vitória FC,1.0,1,0,1,0,0,1,1,0,100,3593
1815,274271,2019-11-09,5530,1903,CD Santa Clara,Sport Lisboa e Benfica,2.0,1,0,1,2,0,0,0,1,3175,6562
1816,274273,2019-11-09,5531,583,FC Famalicão,Moreirense FC,0.0,2,0,3,3,0,0,0,0,2300,1842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1968,274424,2020-06-23,5620,496,Vitória FC,Rio Ave FC,2.0,1,1,1,2,0,0,1,1,3593,100
1969,274423,2020-06-23,1903,5530,Sport Lisboa e Benfica,CD Santa Clara,2.0,0,1,3,4,1,0,0,0,6562,3175
1970,274419,2020-06-23,503,810,FC Porto,Boavista FC,1.0,0,0,4,0,0,2,0,0,6206,2325
1971,274427,2020-06-24,1049,507,CD Tondela,FC Paços de Ferreira,2.0,0,2,1,3,0,1,1,0,1729,1215
1972,274422,2020-06-24,583,5531,Moreirense FC,FC Famalicão,0.0,0,0,1,1,0,0,0,0,1842,2300

In [23]:
df_train=pd.concat([df_final,df_test]).loc[df_final.index.symmetric_difference(df_test.index)]
df_train

,id_match,date,idHomeTeam,idAwayTeam,homeTeam,awayTeam,score,goalHomeTeam_HalfTime,goalAwayTeam_HalfTime,goalHomeTeam_FullTime,goalAwayTeam_FullTime,win_cons_home,win_cons_away,lose_cons_home,lose_cons_away,puissance_homeTeam,puissance_awayTeam
0,267926,2019-08-09,548,523,AS Monaco FC,Olympique Lyonnais,2.0,0,2,0,3,-1,-1,-1,-1,2409,6154
1,267922,2019-08-10,516,547,Olympique de Marseille,Stade de Reims,2.0,0,0,0,2,-1,-1,-1,-1,4008,3054
2,267919,2019-08-10,518,529,Montpellier HSC,Stade Rennais FC 1901,2.0,0,1,0,1,-1,-1,-1,-1,3029,4815
3,267923,2019-08-10,522,530,OGC Nice,Amiens SC,1.0,1,0,2,1,-1,-1,-1,-1,2803,2045
4,267924,2019-08-10,512,511,Stade Brestois 29,Toulouse FC,0.0,1,0,1,1,-1,-1,-1,-1,2156,1065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1807,274265,2019-11-03,1049,498,CD Tondela,Sporting Clube de Portugal,1.0,0,0,1,0,0,3,1,0,1729,5314
1808,274257,2019-11-03,503,5544,FC Porto,CD Aves,1.0,1,0,1,0,0,0,0,7,6206,1159
1809,274258,2019-11-03,5613,5531,Sporting Clube de Braga,FC Famalicão,0.0,0,0,2,2,0,1,1,0,5314,2300
1810,274263,2019-11-04,5568,507,Os Belenenses Futebol,FC Paços de Ferreira,1.0,0,0,1,0,0,0,1,1,1589,1215
1811,274262,2019-11-04,5620,810,Vitória FC,Boavista FC,1.0,0,0,1,0,0,1,0,0,3593,2325

In [24]:
df_train.to_csv(r"Data_Train_Foot.csv", sep=";", encoding='utf-8',index='False')
df_test.to_csv(r"Data_Test_Foot.csv", sep=";", encoding='utf-8',index='False')