In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import json
import urllib.request

In [8]:
df_equipes=pd.DataFrame()
df_points=pd.DataFrame()

## Nettoyage du html pour récupérer les noms et les scores

In [9]:
def recup(equipe,points):
    liste_pts=[]
    liste_equipe=[]
    for row in points:
        val=row.text
        val=val.replace(" ","")
        val=val.replace("\r","")
        val=val.replace("\n","")
        liste_pts.append(int(val))
    
    for row in equipe:
    
        val=row.text
        val=val.replace(" ","")
        val=val.replace("\r","")
        val=val.replace("\n","")
        if val !='City':
            liste_equipe.append(val)
    
    return liste_equipe,liste_pts

## Parcours du html du site

In [10]:
from bs4 import BeautifulSoup
import re
semaine="14"
annee="2020"
index=0
while (index <= 975):
    # L'index représente le nombre d'équipes (le classement)
    url = "https://www.clubworldranking.com/francais/classement-clubs/wd/"+semaine+"/yr/"+annee+"/index/"+str(index)
    html = urllib.request.urlopen(url)

    soup = BeautifulSoup(html, 'lxml')
   

    points= soup.find_all("div", {"class":"points RankingRight"})
    print(points[1])
    equipe= soup.find_all("div", {"class":"col-name lineheigt"})
    
    liste_eq,liste_pts=recup(equipe,points)
    
    df_eq=pd.DataFrame(liste_eq)
    df_eq.columns=["Equipe"]
    df_pts=pd.DataFrame(liste_pts)
    df_pts.columns=["Points"]
    
    df_equipes=pd.concat([df_equipes,df_eq])
    df_points=pd.concat([df_points,df_pts])
    
    # Une page du site possède 25 équipe à la fois
    index=index+25

<div class="points RankingRight">
                                13486
                            </div>
<div class="points RankingRight">
                                7881
                            </div>
<div class="points RankingRight">
                                6351
                            </div>
<div class="points RankingRight">
                                5396
                            </div>
<div class="points RankingRight">
                                4815
                            </div>
<div class="points RankingRight">
                                4234
                            </div>
<div class="points RankingRight">
                                3938
                            </div>
<div class="points RankingRight">
                                3663
                            </div>
<div class="points RankingRight">
                                3267
                            </div>
<div class="points RankingRight">
                                3030
                            </div>
<div class="points RankingRight">
                                2817
                            </div>
<div class="points RankingRight">
                                2592
                            </div>
<div class="points RankingRight">
                                2441
                            </div>
<div class="points RankingRight">
                                2297
                            </div>
<div class="points RankingRight">
                                2108
                            </div>
<div class="points RankingRight">
                                1980
                            </div>
<div class="points RankingRight">
                                1834
                            </div>
<div class="points RankingRight">
                                1735
                            </div>
<div class="points RankingRight">
                                1613
                            </div>
<div class="points RankingRight">
                                1478
                            </div>
<div class="points RankingRight">
                                1340
                            </div>
<div class="points RankingRight">
                                1261
                            </div>
<div class="points RankingRight">
                                1181
                            </div>
<div class="points RankingRight">
                                1098
                            </div>
<div class="points RankingRight">
                                1035
                            </div>
<div class="points RankingRight">
                                980
                            </div>
<div class="points RankingRight">
                                899
                            </div>
<div class="points RankingRight">
                                796
                            </div>
<div class="points RankingRight">
                                689
                            </div>
<div class="points RankingRight">
                                566
                            </div>
<div class="points RankingRight">
                                500
                            </div>
<div class="points RankingRight">
                                409
                            </div>
<div class="points RankingRight">
                                339
                            </div>
<div class="points RankingRight">
                                270
                            </div>
<div class="points RankingRight">
                                232
                            </div>
<div class="points RankingRight">
                                200
                            </div>
<div class="points RankingRight">
                                166
                            </div>
<div class="points RankingRight">
                                144
                            </div>
<div class="points RankingRight">
                                122
                            </div>
<div class="points RankingRight">
                                89
                            </div>

In [11]:
df=pd.concat([df_equipes,df_points],axis=1)
df2=pd.DataFrame()
df2=df2.append(df,ignore_index=True)
df2.head()

       Equipe  Points
0   Liverpool   14695
1    Flamengo   13486
2   Barcelone   13105
3  RiverPlate   11425
4   Palmeiras   11026

## Enregistrement

In [12]:
df2.to_csv(r"Points_Equipes.csv", sep=";", encoding='utf-8')